import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it, vi } from "vitest";

// The registry pulls adapter-core in for I18n; its entry point looks for a js-controller
// and exits the process when there is none — same stub as in the other unit tests.
vi.mock("@iobroker/adapter-core", () => ({
  I18n: {
    getTranslatedObject: vi.fn((key: string) => ({ en: key })),
  },
}));

import { buildMetricDefs } from "./lib/metric-registry";

/**
 * Completeness of test/objects.inventory.json against the adapter's own catalog.
 *
 * The inventory is generated by `npm run test:inventory` from fixtures covering every
 * metric group Beszel 0.18.8 can deliver (test/fixtures/inventory/hub.json). This test is the
 * adapter's side of the fleet contract (CLAUDE_TEMPLATES.md, Objekt-Inventar): every datapoint
 * the registry can create appears under the fully equipped system, every dynamic group has at
 * least one member, and every description that exists is a translation object. Which datapoints
 * carry a description at all is decided in the registry (`descKey`, Design 27: the rest is
 * deliberately self-explaining) — this test only proves the inventory is complete, it does not
 * invent explanations.
 */
const NS = "beszel.0.";
const FULL = `${NS}systems.homelab_server.`;
const LANGS = ["en", "de", "ru", "pt", "nl", "fr", "it", "es", "pl", "uk", "zh-cn"];

function loadInventory(): Record<
  string,
  { type: string; common: Record<string, unknown>; native?: Record<string, unknown> }
> {
  return JSON.parse(readFileSync(join(__dirname, "..", "test", "objects.inventory.json"), "utf8"));
}

describe("object inventory (test/objects.inventory.json)", () => {
  const inventory = loadInventory();
  const ids = Object.keys(inventory);

  it("contains every datapoint of the metric registry for the fully equipped system", () => {
    const missing = buildMetricDefs()
      .map(def => `${FULL}${def.id}`)
      .filter(id => !(id in inventory));
    expect(missing, "registry datapoints missing from the inventory").toEqual([]);
  });

  it("contains every dynamic group with at least one member", () => {
    const groups = [
      "temperature.sensors.",
      "fans.",
      "battery.batteries.",
      "cpu.cores.",
      "network.interfaces.",
      "gpu.0.",
      "gpu.0.engines.",
      "filesystems.",
      "containers.",
    ];
    const empty = groups.filter(g => !ids.some(id => id.startsWith(`${FULL}${g}`) && inventory[id].type === "state"));
    expect(empty, "dynamic groups without a member in the inventory").toEqual([]);
  });

  it("carries the fleet summary and the instance channel from the manifest", () => {
    for (const id of ["info", "info.connection", "info.systemsTotal", "info.systemsOnline", "info.systemsAllUp"]) {
      expect(inventory[`${NS}${id}`], id).toBeDefined();
    }
  });

  it("every description is a complete translation object", () => {
    const bad = ids.filter(id => {
      const desc = inventory[id].common.desc;
      if (desc === undefined || desc === null) {
        return false;
      }
      if (typeof desc !== "object") {
        return true;
      }
      return LANGS.some(l => !(l in (desc as Record<string, string>)));
    });
    expect(bad, "descriptions that are not complete translation objects").toEqual([]);
  });

  it("marks every Hub-named object as API-named and translates every other name", () => {
    const wrong = ids.filter(id => {
      const obj = inventory[id];
      if (obj.type === "device") {
        return false;
      } // the device carries the Hub's system name (Design 26)
      const name = obj.common.name;
      const api = obj.native?.nameSource === "api";
      if (typeof name === "object" && name !== null) {
        return api;
      } // translated names are never API-named
      return !api; // a plain-string name must be declared as the Hub's
    });
    expect(wrong, "plain names without nameSource=api, or translated names marked as api").toEqual([]);
  });

  it("is deterministic in shape: no volatile fields", () => {
    const volatile = ids.filter(id => ["ts", "from", "user", "acl"].some(k => k in inventory[id]));
    expect(volatile).toEqual([]);
  });
});
