import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it, vi } from "vitest";

// The registry pulls adapter-core in for I18n; its entry point looks for a js-controller
// and exits the process when there is none — same stub as in the other unit tests.
vi.mock("@iobroker/adapter-core", () => ({
  I18n: {
    getTranslatedObject: vi.fn((key: string) => ({ en: key })),
    // `common.states` labels go through the plain-string path, not the object one.
    translate: vi.fn((key: string) => key),
  },
}));

import { deviceIcon, ICON_URI_PREFIX, normaliseLineEndings } from "./lib/device-icons";
import { buildMetricDefs } from "./lib/metric-registry";

/**
 * Completeness of test/objects.inventory.json against the adapter's own catalog.
 *
 * The inventory is generated by `npm run test:inventory` from fixtures covering every
 * metric group Beszel 0.19.0 can deliver (test/fixtures/inventory/hub.json), a bare VM without
 * sensors/battery/swap/ZFS and a pending system that never connected. This test is the
 * adapter's side of the fleet contract (CLAUDE_TEMPLATES.md, Objekt-Inventar): every datapoint
 * the registry can create appears under the fully equipped system, every dynamic group has at
 * least one member, and every description that exists is a translation object. WHICH datapoints
 * carry a description is not this test's business (Design 27): the explained ones get their
 * `descKey` here in the code, every other one is declared with a reason in
 * `test/self-explaining.json`, and the fleet gate D08 (`check-object-inventory.py`) refuses an
 * inventory where a datapoint is neither. This test only proves the inventory is complete.
 */
const NS = "beszel.0.";
const FULL = `${NS}systems.homelab_server.`;
const LANGS = ["en", "de", "ru", "pt", "nl", "fr", "it", "es", "pl", "uk", "zh-cn"];

function loadInventory(): Record<
  string,
  { type: string; common: Record<string, unknown>; native?: Record<string, unknown> }
> {
  return JSON.parse(readFileSync(join(__dirname, "..", "test", "objects.inventory.json"), "utf8"));
}

describe("object inventory (test/objects.inventory.json)", () => {
  const inventory = loadInventory();
  const ids = Object.keys(inventory);

  it("contains every datapoint of the metric registry for the fully equipped system", () => {
    const missing = buildMetricDefs()
      .map(def => `${FULL}${def.id}`)
      .filter(id => !(id in inventory));
    expect(missing, "registry datapoints missing from the inventory").toEqual([]);
  });

  it("contains every dynamic group with at least one member", () => {
    const groups = [
      "temperature.sensors.",
      "fans.",
      "zfs.",
      "battery.batteries.",
      "cpu.cores.",
      "network.interfaces.",
      "gpu.0.",
      "gpu.0.engines.",
      "filesystems.",
      "containers.",
    ];
    const empty = groups.filter(g => !ids.some(id => id.startsWith(`${FULL}${g}`) && inventory[id].type === "state"));
    expect(empty, "dynamic groups without a member in the inventory").toEqual([]);
  });

  it("carries the fleet summary and the instance channel from the manifest", () => {
    for (const id of ["info", "info.connection", "info.systemsTotal", "info.systemsOnline", "info.systemsAllUp"]) {
      expect(inventory[`${NS}${id}`], id).toBeDefined();
    }
  });

  it("every description is a complete translation object", () => {
    const bad = ids.filter(id => {
      const desc = inventory[id].common.desc;
      if (desc === undefined || desc === null) {
        return false;
      }
      if (typeof desc !== "object") {
        return true;
      }
      return LANGS.some(l => !(l in (desc as Record<string, string>)));
    });
    expect(bad, "descriptions that are not complete translation objects").toEqual([]);
  });

  it("marks every Hub-named object as API-named and translates every other name", () => {
    const wrong = ids.filter(id => {
      const obj = inventory[id];
      const name = obj.common.name;
      const api = obj.native?.nameSource === "api";
      if (typeof name === "object" && name !== null) {
        return api;
      } // translated names are never API-named
      return !api; // a plain-string name must be declared as the Hub's
    });
    expect(wrong, "plain names without nameSource=api, or translated names marked as api").toEqual([]);
  });

  it("gives every system device an inline OS pictogram that IS one of the shipped files (v0.18.0)", () => {
    const devices = ids.filter(id => inventory[id].type === "device" && /^beszel\.0\.systems\.[^.]+$/.test(id));
    expect(devices.length, "four fixture systems").toBe(4);
    const files = ["linux.svg", "macos.svg", "windows.svg", "freebsd.svg", "server.svg"];
    const known = new Map(
      files.map(f => [
        `${ICON_URI_PREFIX}${Buffer.from(normaliseLineEndings(readFileSync(join(__dirname, "..", "admin", "icons", f), "utf8"))).toString("base64")}`,
        f,
      ]),
    );
    const byDevice: Record<string, string | undefined> = {};
    for (const id of devices) {
      const icon = inventory[id].common.icon;
      expect(typeof icon, `${id} carries an icon`).toBe("string");
      byDevice[id] = known.get(icon as string);
      expect(byDevice[id], `${id}: the icon is one of the shipped files, embedded byte for byte`).toBeDefined();
    }
    // Linux details → Tux, FreeBSD details → the daemon, a pending system without details → the rack.
    expect(byDevice[`${NS}systems.homelab_server`]).toBe("linux.svg");
    expect(byDevice[`${NS}systems.build_vm`]).toBe("linux.svg");
    expect(byDevice[`${NS}systems.backup_nas`]).toBe("freebsd.svg");
    expect(byDevice[`${NS}systems.new_host`]).toBe("server.svg");
    expect(deviceIcon(3)).toBe([...known.entries()].find(([, f]) => f === "freebsd.svg")![0]);
  });

  it("proves ABSENCE too: the bare VM has no sensor, battery, swap, ZFS-ARC or disk-I/O datapoints (v0.18.0)", () => {
    const vm = `${NS}systems.build_vm.`;
    const vmIds = ids.filter(id => id.startsWith(vm));
    expect(vmIds.length, "the VM has a tree").toBeGreaterThan(10);
    for (const absent of [
      "temperature",
      "battery",
      "memory.swap_used",
      "memory.swap_total",
      "memory.zfs_arc",
      "disk.io_util",
      "fans",
      "gpu",
      "containers",
      "filesystems",
      "zfs",
      "smart",
      "services",
    ]) {
      expect(inventory[`${vm}${absent}`], `${absent} must not exist on a host without it`).toBeUndefined();
    }
    // …while the plain rates are there and read 0, not null (the values are not in the inventory,
    // but the objects are).
    expect(inventory[`${vm}network.sent`]).toBeDefined();
    expect(inventory[`${vm}disk.read`]).toBeDefined();
    // The pending system is a device with its info channel only.
    const pending = ids.filter(id => id.startsWith(`${NS}systems.new_host`));
    expect(pending.sort()).toEqual([
      `${NS}systems.new_host`,
      `${NS}systems.new_host.info`,
      `${NS}systems.new_host.info.online`,
      `${NS}systems.new_host.info.status`,
    ]);
  });

  it("carries none of the retired peak datapoints (v0.18.0)", () => {
    const peaks = ids.filter(id => /\.(cpu|memory)\.peak$|\.(read|write|sent|recv)_peak$/.test(id));
    expect(peaks).toEqual([]);
  });

  it("is deterministic in shape: no volatile fields", () => {
    const volatile = ids.filter(id => ["ts", "from", "user", "acl"].some(k => k in inventory[id]));
    expect(volatile).toEqual([]);
  });
});
